#!/bin/ash

# generate host keys if not present
ssh-keygen -A

/lib/wildfly/bin/standalone.sh -b 0.0.0.0 -Djboss.http.port=8081 &

# do not detach (-D), log to stderr (-e), passthrough other arguments
exec /usr/sbin/sshd -D -e "$@"
